name: Go TDD

on:
  push:
    branches-ignore:
      - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        arch:
          - amd64
          - arm64

        exclude:
          # Windows ARM64 runner tidak tersedia sebagai runner standar
          - os: windows-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.26
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: true

      - name: Show environment
        run: |
          go version
          go env GOOS GOARCH

      - name: Run tests
        env:
          GOARCH: ${{ matrix.arch }}
        run: go test -v ./...
